--Coded in SQLite 3

CREATE TABLE myblog (
	ID INTEGER,
	Title VARCHAR(200) NOT NULL,
	Main_text VARCHAR(1000) NOT NULL,
	Author TEXT NOT NULL,
	Date_posted DATE NOT NULL,
	PRIMARY KEY (ID)
);	

CREATE TABLE keywords (
	ID INTEGER NOT NULL,
	Keyword TEXT NOT NULL,
	PRIMARY KEY (ID,Keyword),
	FOREIGN KEY(ID) REFERENCES myblog(ID) ON DELETE CASCADE
);
